# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuma/url-launcher/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuma/url-launcher/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuma/url-launcher/src/CMakeFiles /home/yuma/url-launcher/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuma/url-launcher/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mytool

# Build rule for target.
mytool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mytool
.PHONY : mytool

# fast build rule for target.
mytool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/build
.PHONY : mytool/fast

SQLiteDB.o: SQLiteDB.cpp.o
.PHONY : SQLiteDB.o

# target to build an object file
SQLiteDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/SQLiteDB.cpp.o
.PHONY : SQLiteDB.cpp.o

SQLiteDB.i: SQLiteDB.cpp.i
.PHONY : SQLiteDB.i

# target to preprocess a source file
SQLiteDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/SQLiteDB.cpp.i
.PHONY : SQLiteDB.cpp.i

SQLiteDB.s: SQLiteDB.cpp.s
.PHONY : SQLiteDB.s

# target to generate assembly for a file
SQLiteDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/SQLiteDB.cpp.s
.PHONY : SQLiteDB.cpp.s

URLLauncher.o: URLLauncher.cpp.o
.PHONY : URLLauncher.o

# target to build an object file
URLLauncher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/URLLauncher.cpp.o
.PHONY : URLLauncher.cpp.o

URLLauncher.i: URLLauncher.cpp.i
.PHONY : URLLauncher.i

# target to preprocess a source file
URLLauncher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/URLLauncher.cpp.i
.PHONY : URLLauncher.cpp.i

URLLauncher.s: URLLauncher.cpp.s
.PHONY : URLLauncher.s

# target to generate assembly for a file
URLLauncher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/URLLauncher.cpp.s
.PHONY : URLLauncher.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mytool.dir/build.make CMakeFiles/mytool.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mytool"
	@echo "... SQLiteDB.o"
	@echo "... SQLiteDB.i"
	@echo "... SQLiteDB.s"
	@echo "... URLLauncher.o"
	@echo "... URLLauncher.i"
	@echo "... URLLauncher.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

